export const products = [
  {
    id: "kukirin-g2",
    slug: "kukirin-g2",
    name: "KuKirin G2",
    price: 14.99,
    category: "3D Printed Model",
    description: "A detailed 3D-printed miniature model of the KuKirin G2, designed as a display piece for your desk or shelf.",
    material: "PLA",
    productionTime: "3–5 business days",
    colors: ["Black", "White"],
    sizes: ["Standard"],
    customization: true,
    image: null
  },
  {
    id: "kukirin-g4",
    slug: "kukirin-g4",
    name: "KuKirin G4",
    price: 17.99,
    category: "3D Printed Model",
    description: "A detailed 3D-printed miniature model inspired by the KuKirin G4, perfect for collectors and display.",
    material: "PLA",
    productionTime: "3–5 business days",
    colors: ["Black", "White"],
    sizes: ["Standard"],
    customization: true,
    image: null
  },
  {
    id: "e-box",
    slug: "e-box",
    name: "E-Box",
    price: 19.99,
    category: "3D Printed Model",
    description: "A 3D-printed miniature E-Box model made as a compact decorative piece for your collection.",
    material: "PLA",
    productionTime: "3–5 business days",
    colors: ["Black", "White"],
    sizes: ["Standard"],
    customization: true,
    image: null
  },
  {
    id: "sur-ron",
    slug: "sur-ron",
    name: "Sur-Ron",
    price: 24.99,
    category: "3D Printed Model",
    description: "A detailed 3D-printed Sur-Ron miniature model created for display, collecting, and decoration.",
    material: "PLA",
    productionTime: "3–5 business days",
    colors: ["Black", "White"],
    sizes: ["Standard"],
    customization: true,
    image: null
  },
  {
    id: "stark-varg",
    slug: "stark-varg",
    name: "Stark VARG",
    price: 29.99,
    category: "3D Printed Model",
    description: "A detailed 3D-printed Stark VARG miniature model made as a display piece for collectors and enthusiasts.",
    material: "PLA",
    productionTime: "3–5 business days",
    colors: ["Black", "White"],
    sizes: ["Standard"],
    customization: true,
    image: null
  }
];
